import { describe, expect, test } from "bun:test";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";

import { CommandRunnerLive } from "../../src/process/command-runner.ts";
import { makeGitIssueCheckpointService } from "../../src/git/issue-checkpoint.ts";
import {
    GitPushError,
    GitPushFailurePolicy,
    GitPushFailureKind,
    makeGitIssueOperationsService,
} from "../../src/git/issue-operations.ts";

const runGit = (
    repositoryPath: string,
    args: ReadonlyArray<string>,
    trimStdout = true,
) =>
    CommandRunnerLive.run("git", ["-C", repositoryPath, ...args], {
        trimStdout,
    });

const setupRepository = async () => {
    const repositoryPath = await mkdtemp(
        join(tmpdir(), "ralphie-git-operations-"),
    );
    await runGit(repositoryPath, ["init", "-b", "main"]);
    await runGit(repositoryPath, [
        "config",
        "user.email",
        "ralphie@example.test",
    ]);
    await runGit(repositoryPath, ["config", "user.name", "Ralphie Tests"]);
    await writeFile(
        join(repositoryPath, "binary.dat"),
        Buffer.from([0, 1, 2, 3]),
    );
    await runGit(repositoryPath, ["add", "--all"]);
    await runGit(repositoryPath, ["commit", "-m", "initial"]);
    return repositoryPath;
};

describe("deterministic Git issue operations", () => {
    test("stages all changes, detects the staged set, and preserves the exact binary diff", async () => {
        const repositoryPath = await setupRepository();
        try {
            await writeFile(
                join(repositoryPath, "binary.dat"),
                Buffer.from([0, 9, 8, 7]),
            );
            await writeFile(
                join(repositoryPath, "untracked.txt"),
                "new file\n",
            );
            const operations = makeGitIssueOperationsService();
            expect(await operations.hasStagedChanges(repositoryPath)).toBe(
                false,
            );
            await operations.stageAll(repositoryPath);
            const [actualDiff, expectedDiff] = await Promise.all([
                operations.readStagedBinaryDiff(repositoryPath),
                runGit(
                    repositoryPath,
                    ["diff", "--cached", "--binary"],
                    false,
                ).then((result) => result.stdout),
            ]);
            expect(await operations.hasStagedChanges(repositoryPath)).toBe(
                true,
            );
            expect(actualDiff).toBe(expectedDiff);
            expect(actualDiff).toContain("GIT binary patch");
            expect(actualDiff).toContain("untracked.txt");
        } finally {
            await rm(repositoryPath, { recursive: true, force: true });
        }
    });

    test("commits and pushes without force, then verifies origin", async () => {
        const repositoryPath = await setupRepository();
        const remotePath = await mkdtemp(join(tmpdir(), "ralphie-git-remote-"));
        try {
            await runGit(remotePath, ["init", "--bare"]);
            await runGit(repositoryPath, [
                "remote",
                "add",
                "origin",
                remotePath,
            ]);
            await runGit(repositoryPath, [
                "push",
                "--no-force",
                "origin",
                "main",
            ]);
            await writeFile(
                join(repositoryPath, "change.txt"),
                "implementation\n",
            );
            const operations = makeGitIssueOperationsService();
            await operations.stageAll(repositoryPath);
            const result = await operations.commit(repositoryPath, {
                subject: "implement issue behavior",
                body: "This change was generated by the issue workflow.",
            });
            expect(result.sha).toMatch(/^[0-9a-f]{40}$/);
            await operations.push(repositoryPath, "main", result.sha);
            expect(
                (await runGit(remotePath, ["rev-parse", "refs/heads/main"]))
                    .stdout,
            ).toBe(result.sha);
            expect(
                (await runGit(repositoryPath, ["status", "--porcelain=v1"]))
                    .stdout,
            ).toBe("");
        } finally {
            await rm(repositoryPath, { recursive: true, force: true });
            await rm(remotePath, { recursive: true, force: true });
        }
    });

    test("classifies non-fast-forward rejection and halts instead of retrying", async () => {
        const repositoryPath = await setupRepository();
        const remotePath = await mkdtemp(join(tmpdir(), "ralphie-git-remote-"));
        const otherRepositoryPath = await mkdtemp(
            join(tmpdir(), "ralphie-git-other-"),
        );
        try {
            await runGit(remotePath, ["init", "--bare"]);
            await runGit(repositoryPath, [
                "remote",
                "add",
                "origin",
                remotePath,
            ]);
            await runGit(repositoryPath, [
                "push",
                "--no-force",
                "origin",
                "main",
            ]);
            await runGit(otherRepositoryPath, ["clone", remotePath, "."]);
            await runGit(otherRepositoryPath, [
                "config",
                "user.email",
                "other@example.test",
            ]);
            await runGit(otherRepositoryPath, [
                "config",
                "user.name",
                "Other Tests",
            ]);
            await writeFile(
                join(otherRepositoryPath, "remote.txt"),
                "remote\n",
            );
            await runGit(otherRepositoryPath, ["add", "--all"]);
            await runGit(otherRepositoryPath, [
                "commit",
                "-m",
                "advance remote",
            ]);
            await runGit(otherRepositoryPath, [
                "push",
                "--no-force",
                "origin",
                "main",
            ]);
            await writeFile(join(repositoryPath, "local.txt"), "local\n");
            const operations = makeGitIssueOperationsService();
            await operations.stageAll(repositoryPath);
            const commit = await operations.commit(repositoryPath, {
                subject: "local work",
            });
            await expect(
                operations.push(repositoryPath, "main", commit.sha),
            ).rejects.toMatchObject({
                kind: GitPushFailureKind.NonFastForward,
                policy: GitPushFailurePolicy.Halt,
                branch: "main",
            });
        } finally {
            await rm(repositoryPath, { recursive: true, force: true });
            await rm(remotePath, { recursive: true, force: true });
            await rm(otherRepositoryPath, { recursive: true, force: true });
        }
    });

    test("runs checkpoint, restore, commit, and push through one checkout flow", async () => {
        const repositoryPath = await setupRepository();
        const remotePath = await mkdtemp(join(tmpdir(), "ralphie-git-remote-"));
        try {
            await runGit(remotePath, ["init", "--bare"]);
            await runGit(repositoryPath, [
                "remote",
                "add",
                "origin",
                remotePath,
            ]);
            await runGit(repositoryPath, [
                "push",
                "--no-force",
                "origin",
                "main",
            ]);
            const checkpoints = makeGitIssueCheckpointService();
            const checkpoint = await checkpoints.capture(
                repositoryPath,
                "main",
            );
            await writeFile(
                join(repositoryPath, "temporary.bin"),
                Buffer.from([0, 4, 5, 6]),
            );
            const operations = makeGitIssueOperationsService();
            await operations.stageAll(repositoryPath);
            expect(
                await operations.readStagedBinaryDiff(repositoryPath),
            ).toContain("GIT binary patch");
            await checkpoints.restore(repositoryPath, checkpoint);
            expect(
                (await runGit(repositoryPath, ["status", "--porcelain=v1"]))
                    .stdout,
            ).toBe("");
            await writeFile(
                join(repositoryPath, "final.txt"),
                "final implementation\n",
            );
            await operations.stageAll(repositoryPath);
            const commit = await operations.commit(repositoryPath, {
                subject: "finish issue flow",
            });
            await operations.push(repositoryPath, "main", commit.sha);
            expect(
                (await runGit(remotePath, ["rev-parse", "refs/heads/main"]))
                    .stdout,
            ).toBe(commit.sha);
        } finally {
            await rm(repositoryPath, { recursive: true, force: true });
            await rm(remotePath, { recursive: true, force: true });
        }
    });
});