import { HandOffReason } from "./decisions.ts";

/** The human-facing triage state an issue moves to when it is handed off. */
export type HandOffTarget = "needs-info" | "ready-for-human";

/** Reasons that wait on the reporter; every other reason needs a human to act. */
const NEEDS_INFO_REASONS: ReadonlySet<HandOffReason> = new Set([
    HandOffReason.MissingInformation,
    HandOffReason.ConflictingRequirements,
    HandOffReason.CannotReproduce,
    HandOffReason.OutdatedPremise,
]);

export const handOffTarget = (reason: HandOffReason): HandOffTarget =>
    NEEDS_INFO_REASONS.has(reason) ? "needs-info" : "ready-for-human";

/** The disclaimer every Ralphie issue comment starts with. */
export const AI_DISCLAIMER = "> *This was generated by AI during triage.*";

/** Prefix an issue comment body with the AI disclaimer. */
export const withDisclaimer = (body: string): string =>
    `${AI_DISCLAIMER}\n\n${body}`;

/**
 * The label names a hand-off applies. `replaces` lists every triage state
 * label so the hand-off leaves the issue with exactly one state label.
 */
export type HandOffLabels = {
    readonly "needs-info": string;
    readonly "ready-for-human": string;
    readonly replaces: ReadonlyArray<string>;
};

export const CANONICAL_HAND_OFF_LABELS: HandOffLabels = {
    "needs-info": "needs-info",
    "ready-for-human": "ready-for-human",
    replaces: [
        "needs-triage",
        "needs-info",
        "ready-for-agent",
        "ready-for-human",
        "wontfix",
    ],
};

export const handOffLabelsFrom = (
    labels: Readonly<
        Record<
            | "needs-triage"
            | "needs-info"
            | "ready-for-agent"
            | "ready-for-human"
            | "wontfix",
            string
        >
    >,
): HandOffLabels => ({
    "needs-info": labels["needs-info"],
    "ready-for-human": labels["ready-for-human"],
    replaces: [
        labels["needs-triage"],
        labels["needs-info"],
        labels["ready-for-agent"],
        labels["ready-for-human"],
        labels.wontfix,
    ],
});

export type HandOffContent = {
    readonly reason: HandOffReason;
    readonly summary: string;
    readonly evidence: ReadonlyArray<string>;
    readonly questions: ReadonlyArray<string>;
    /** Where the diagnostics for this hand-off were preserved, if anywhere. */
    readonly diagnosticsPath?: string;
};

const bullets = (items: ReadonlyArray<string>): string =>
    items.map((item) => `- ${item}`).join("\n");

const triageNotes = (content: HandOffContent): string =>
    [
        "## Triage Notes",
        "",
        "**What we've established so far:**",
        "",
        bullets([content.summary, ...content.evidence]),
        "",
        "**What we still need from you:**",
        "",
        bullets(content.questions),
    ].join("\n");

/**
 * An Agent-Brief-style write-up. It deliberately avoids the `## Agent Brief`
 * heading, which marks the contract an implementer works from.
 */
const humanWriteUp = (content: HandOffContent): string =>
    [
        "## Hand-off",
        "",
        `**Reason:** ${content.reason}`,
        `**Summary:** ${content.summary}`,
        "",
        "**What was tried:**",
        "",
        bullets(content.evidence),
        "",
        "**What a human needs to decide or do:**",
        "",
        bullets(content.questions),
        ...(content.diagnosticsPath === undefined
            ? []
            : ["", `**Diagnostics:** \`${content.diagnosticsPath}\``]),
    ].join("\n");

/** The comment Ralphie posts when it hands an issue off. */
export const renderHandOffComment = (content: HandOffContent): string =>
    withDisclaimer(
        handOffTarget(content.reason) === "needs-info"
            ? triageNotes(content)
            : humanWriteUp(content),
    );