import { describe, expect, test } from "bun:test";
import type { Octokit } from "octokit";

import { makeGitHubHandOffService } from "../../src/github/adapters/hand-off.ts";
import type { GitHubSession } from "../../src/github/adapters/session.ts";

type Recorded = { readonly call: string; readonly args: unknown };

const fakeClient = (input: {
    readonly existing?: ReadonlyArray<{
        readonly id: number;
        readonly body: string;
    }>;
    readonly missingLabels?: ReadonlyArray<string>;
    readonly recorded: Recorded[];
}): GitHubSession => {
    const { recorded } = input;
    const listComments = Symbol("listComments");
    const client = {
        paginate: async (method: symbol) => {
            if (method !== listComments) throw new Error("unexpected list");
            return input.existing ?? [];
        },
        rest: {
            issues: {
                listComments,
                createComment: async (args: unknown) => {
                    recorded.push({ call: "createComment", args });
                    return {};
                },
                updateComment: async (args: unknown) => {
                    recorded.push({ call: "updateComment", args });
                    return {};
                },
                addLabels: async (args: unknown) => {
                    recorded.push({ call: "addLabels", args });
                    return {};
                },
                removeLabel: async (args: { readonly name: string }) => {
                    recorded.push({ call: "removeLabel", args });
                    if (input.missingLabels?.includes(args.name)) {
                        throw Object.assign(new Error("Not Found"), {
                            status: 404,
                        });
                    }
                    return {};
                },
            },
        },
    } as unknown as Octokit;
    return { client: () => client };
};

const handOff = {
    body: "> *This was generated by AI during triage.*\n\n## Hand-off",
    label: "ready-for-human",
    replaceLabels: ["ready-for-agent", "needs-info", "ready-for-human"],
};

describe("GitHub hand-off", () => {
    test("posts the comment once and swaps the state label", async () => {
        const recorded: Recorded[] = [];
        const service = makeGitHubHandOffService(fakeClient({ recorded }));

        const result = await service.handOff("owner/repo", 42, handOff);

        expect(result).toEqual({ comment: "created" });
        const created = recorded.find(({ call }) => call === "createComment");
        const body = (created?.args as { body: string }).body;
        expect(
            body.startsWith("> *This was generated by AI during triage.*"),
        ).toBe(true);
        expect(body).toContain("<!-- ralphie:hand-off issue=42 -->");
        expect(
            recorded
                .filter(({ call }) => call !== "createComment")
                .map(({ call, args }) => [
                    call,
                    (args as { name?: string }).name ??
                        (args as { labels?: string[] }).labels,
                ]),
        ).toEqual([
            ["addLabels", ["ready-for-human"]],
            ["removeLabel", "ready-for-agent"],
            ["removeLabel", "needs-info"],
        ]);
    });

    test("ignores state labels the issue does not carry", async () => {
        const recorded: Recorded[] = [];
        const service = makeGitHubHandOffService(
            fakeClient({ recorded, missingLabels: ["needs-info"] }),
        );

        await service.handOff("owner/repo", 42, handOff);

        expect(recorded.map(({ call }) => call)).toContain("addLabels");
    });

    test("updates its own earlier comment instead of posting another", async () => {
        const recorded: Recorded[] = [];
        const service = makeGitHubHandOffService(
            fakeClient({
                recorded,
                existing: [
                    {
                        id: 7,
                        body: "old\n\n<!-- ralphie:hand-off issue=42 -->",
                    },
                ],
            }),
        );

        const result = await service.handOff("owner/repo", 42, handOff);

        expect(result).toEqual({ comment: "updated" });
        expect(recorded.map(({ call }) => call)).not.toContain("createComment");
        expect(recorded.map(({ call }) => call)).toContain("updateComment");
    });

    test("fails closed when the marker is ambiguous", async () => {
        const recorded: Recorded[] = [];
        const marker = "<!-- ralphie:hand-off issue=42 -->";
        const service = makeGitHubHandOffService(
            fakeClient({
                recorded,
                existing: [
                    { id: 1, body: marker },
                    { id: 2, body: marker },
                ],
            }),
        );

        await expect(
            service.handOff("owner/repo", 42, handOff),
        ).rejects.toThrow("ambiguous");
        expect(recorded).toEqual([]);
    });
});