import { describe, expect, test } from "bun:test";
import type { Octokit } from "octokit";

import type { GitHubSession } from "../../src/github/adapters/session.ts";
import { makeGitHubTriageService } from "../../src/github/adapters/triage.ts";

type Recorded = { readonly call: string; readonly args: unknown };

const fakeClient = (input: {
    readonly existing?: ReadonlyArray<{
        readonly id: number;
        readonly body: string;
    }>;
    readonly recorded: Recorded[];
}): GitHubSession => {
    const listComments = Symbol("listComments");
    const client = {
        paginate: async (method: symbol) => {
            if (method !== listComments) throw new Error("unexpected list");
            return input.existing ?? [];
        },
        rest: {
            issues: {
                listComments,
                createComment: async (args: unknown) => {
                    input.recorded.push({ call: "createComment", args });
                    return {};
                },
                addLabels: async (args: unknown) => {
                    input.recorded.push({ call: "addLabels", args });
                    return {};
                },
                removeLabel: async (args: unknown) => {
                    input.recorded.push({ call: "removeLabel", args });
                    return {};
                },
            },
        },
    } as unknown as Octokit;
    return { client: () => client };
};

const brief = {
    body: "> *This was generated by AI during triage.*\n\n## Agent Brief\n\nDo it.",
    label: "ready-for-agent",
    replaceLabels: ["needs-triage", "needs-info", "ready-for-agent"],
};

describe("GitHub triage", () => {
    test("posts the brief and moves the issue to ready-for-agent", async () => {
        const recorded: Recorded[] = [];
        const service = makeGitHubTriageService(fakeClient({ recorded }));

        const result = await service.promote("owner/repo", 42, brief);

        expect(result).toEqual({ comment: "created" });
        const created = recorded.find(({ call }) => call === "createComment");
        expect((created?.args as { body: string }).body).toContain(
            "## Agent Brief",
        );
        expect(recorded.map(({ call }) => call)).toEqual([
            "createComment",
            "addLabels",
            "removeLabel",
            "removeLabel",
        ]);
    });

    test("does not post the same brief twice after a restart", async () => {
        const recorded: Recorded[] = [];
        const first: Recorded[] = [];
        await makeGitHubTriageService(fakeClient({ recorded: first })).promote(
            "owner/repo",
            42,
            brief,
        );
        const posted = (first[0]?.args as { body: string }).body;
        const service = makeGitHubTriageService(
            fakeClient({ recorded, existing: [{ id: 3, body: posted }] }),
        );

        const result = await service.promote("owner/repo", 42, brief);

        expect(result).toEqual({ comment: "unchanged" });
        expect(recorded.map(({ call }) => call)).not.toContain("createComment");
        expect(recorded.map(({ call }) => call)).toContain("addLabels");
    });

    test("a changed brief is posted as a new comment so the newest wins", async () => {
        const recorded: Recorded[] = [];
        const service = makeGitHubTriageService(
            fakeClient({
                recorded,
                existing: [
                    {
                        id: 3,
                        body: "old brief\n\n<!-- ralphie:agent-brief issue=42 -->",
                    },
                ],
            }),
        );

        const result = await service.promote("owner/repo", 42, brief);

        expect(result).toEqual({ comment: "created" });
    });

    test("explains an already implemented request once", async () => {
        const recorded: Recorded[] = [];
        const service = makeGitHubTriageService(fakeClient({ recorded }));

        const result = await service.explainImplemented(
            "owner/repo",
            42,
            "> *This was generated by AI during triage.*\n\nIt lives in src/a.ts.",
        );

        expect(result).toEqual({ comment: "created" });
        expect(recorded.map(({ call }) => call)).toEqual(["createComment"]);
    });
});