import { describe, expect, test } from "bun:test";

import {
    buildImplementationPrompt,
    buildReviewFixPrompt,
    buildTriagePrompt,
    PROMPT_ISSUE_COMMENT_BODY_LIMIT,
    PROMPT_ISSUE_COMMENT_COUNT_LIMIT,
} from "../../src/agent/prompts.ts";
import type {
    GitHubIssue,
    GitHubIssueComment,
} from "../../src/github/domain.ts";
import {
    ReviewFindingSeverity,
    ReviewVerdict,
} from "../../src/issues/domain/decisions.ts";

const comment = (id: number, body: string): GitHubIssueComment => ({
    id,
    body,
    updatedAt: "2026-08-28T00:00:00.000Z",
});

const issueWith = (
    comments: ReadonlyArray<GitHubIssueComment>,
): GitHubIssue => ({
    number: 7,
    title: "Add a thing",
    url: "https://github.com/owner/repo/issues/7",
    body: "Original body text.",
    labels: [],
    comments,
    commentCount: comments.length,
});

const promptFor = (issue: GitHubIssue): string =>
    buildImplementationPrompt({
        issue,
        repositoryPath: "/work/repo",
        targetBranch: "main",
        implementInvocation: "/implement",
    });

describe("implementation prompt", () => {
    test("invokes the implement skill with the overlay", () => {
        const prompt = promptFor(issueWith([]));
        expect(prompt).toContain("/implement");
        expect(prompt).toMatch(/do not commit/i);
        expect(prompt).toMatch(/skip the closing code review/i);
        expect(prompt).toContain("commitMessage");
        expect(prompt).toContain("needs_attention");
    });

    test("uses the issue body as the contract without an Agent Brief", () => {
        const prompt = promptFor(issueWith([comment(1, "just chatting")]));
        expect(prompt).toContain("<contract>");
        expect(prompt).toContain("Original body text.");
        expect(prompt).not.toContain("Agent Brief");
    });

    test("includes the latest Agent Brief in full even past every comment limit", () => {
        const longBrief = `## Agent Brief\n\n${"detail line\n".repeat(PROMPT_ISSUE_COMMENT_BODY_LIMIT)}END-OF-BRIEF`;
        const comments = [
            comment(1, "## Agent Brief\n\nOLD-BRIEF"),
            comment(2, longBrief),
            ...Array.from(
                { length: PROMPT_ISSUE_COMMENT_COUNT_LIMIT + 5 },
                (_, index) => comment(10 + index, `chatter ${index}`),
            ),
        ];
        const prompt = promptFor(issueWith(comments));
        expect(prompt).toContain("END-OF-BRIEF");
        expect(prompt).not.toContain("OLD-BRIEF");
        expect(prompt).not.toContain("issue comment body truncated");
        expect(prompt.indexOf("<agent-brief>")).toBeLessThan(
            prompt.indexOf("Original body text."),
        );
    });

    test("finds an Agent Brief that starts with the AI disclaimer", () => {
        const prompt = promptFor(
            issueWith([
                comment(
                    1,
                    "> *This was generated by AI during triage.*\n\n## Agent Brief\n\nDISCLAIMED-BRIEF",
                ),
            ]),
        );
        expect(prompt).toContain("<agent-brief>");
        expect(prompt).toContain("DISCLAIMED-BRIEF");
    });
});

describe("triage prompt", () => {
    const prompt = buildTriagePrompt({
        issue: issueWith([]),
        repositoryPath: "/work/repo",
        targetBranch: "main",
        triageInvocation: "/triage",
        bucket: "needs-triage",
        labels: {
            "needs-triage": "needs-triage",
            "needs-info": "needs-info",
            "ready-for-agent": "ready-for-agent",
            "ready-for-human": "ready-for-human",
            wontfix: "wontfix",
        },
    });

    test("invokes the triage skill with an overlay that skips the maintainer steps", () => {
        expect(prompt).toContain("/triage");
        expect(prompt).toMatch(/skip .*grilling/is);
        expect(prompt).toMatch(/never write to\s+\.out-of-scope/i);
        expect(prompt).toContain("## Agent Brief");
    });

    test("offers no way to apply wontfix", () => {
        expect(prompt).toMatch(/never apply or recommend\s+"wontfix"/i);
    });
});
describe("review fix prompt", () => {
    test("hands a fresh fixer the candidate diff, not a staged diff", () => {
        const prompt = buildReviewFixPrompt({
            issue: issueWith([]),
            repositoryPath: "/work/repo",
            targetBranch: "main",
            candidateDiff: "diff --git a/x.ts b/x.ts\n+CANDIDATE-LINE",
            review: {
                verdict: ReviewVerdict.ChangesRequested,
                summary: "Needs a guard.",
                findings: [
                    {
                        severity: ReviewFindingSeverity.Blocking,
                        description: "Missing null check.",
                    },
                ],
            },
        });
        expect(prompt).toContain(
            "<candidate-diff>\ndiff --git a/x.ts b/x.ts\n+CANDIDATE-LINE\n</candidate-diff>",
        );
        expect(prompt).toMatch(/issue checkpoint to the reviewed candidate/);
        expect(prompt).not.toContain("staged-diff");
        expect(prompt).toContain("Missing null check.");
    });
});